### ISSUE TITLE
Add a summary of how many years a committee has been active to the detail page

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-campaign-browser#147]
i.e. (2006-2009) or (2014-Present)

**Comment by caseymm** [comment]
Do we want to start with the earliest filing, or the earliest filing with a dollar value above zero? For instance, committee with id 8427, has filings listed as early as 1999, but the earliest filings listed in the yearly table above start in 2002 since those are the first ones with a relevant dollar value.

**Comment by caseymm** [comment]
@palewire
