### ISSUE TITLE
Where is this live? I want a screenshot? Tell me more about the Data? This looks amazing.

### ISSUE THREAD

**Issue by mlissner** [california-civic-data-coalition/django-calaccess-campaign-browser#229]
Just another civic data hacker here. Just found your project and it looks great. The issue tracker is especially well-populated! 

I'm too lazy to install this myself without seeing what it is that even loads once it's installed. Is this live somewhere? Are there screenshots so I can see what the data looks like once it's loaded? If it's mostly just data, is the data explained somewhere?

**Comment by palewire** [comment]
Hello!

I don't have a live version of it running anywhere, though someone else might. Mainly that's because we are a long way from perfecting the many filters, transformations and corrections necessary to make the raw data presentable. And we don't want to put anything online that we don't believe is 100% accurate.

However, if you were to spin it up you would see the beginnings of a user interface aimed at serving power users. It is similar to other campaign finance sites, but more emphasis is placed on bulk downloads an more complex slicing and dicing than the standard click and search.

You can see some screenshots in [this blog post](http://www.californiacivicdata.org/2014/09/24/hello-world/) we put out for the initial release.

I think ultimately we might split this application in half, separating the data transformations and cleanup from the user interface. But for now they live together. 

That work, and a whole hell of a lot of documentation, will be the focus of a lead developer we are [currently hiring](http://www.californiacivicdata.org/2015/07/22/knight-news-challenge/) thanks to a grant from the Knight News Challenge.

**Comment by palewire** [comment]
Well wait. Let me leave this open until you tell me if I actually answered your question!

**Comment by mlissner** [comment]
Yeah, that's more or less what I was looking for, thanks.

Job looks like it'd be a fun one. We got some of that Knight money too though, so we have our own things going on over at freelawproject.

Thanks for the response. We may send you an email to get in touch for some other stuff too.

**Comment by palewire** [comment]
Great!
